name: GakuseAI
options:
  bundleIdPrefix: ai.gakuse
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  defaultConfig: Debug

settings:
  base:
    PRODUCT_NAME: GakuseAI
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  GakuseAI:
    type: application
    platform: iOS
    sources:
      - GakuseAI
    settings:
      base:
        INFOPLIST_FILE: GakuseAI/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ai.gakuse.app
        CODE_SIGN_ENTITLEMENTS: GakuseAI/GakuseAI.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: GakuseAI/Info.plist
      properties:
        CFBundleDisplayName: GakuseAI
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: AccentColor
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiredDeviceCapabilities:
          - arm64

  GakuseAITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - GakuseAITests
    dependencies:
      - target: GakuseAI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.gakuse.app.tests

  GakuseAIUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - GakuseAIUITests
    dependencies:
      - target: GakuseAI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.gakuse.app.uitests
